title: Site

columns:
  main:
    width: 2/2
    sections:
      pages:
        headline: Hauptseiten
        type: pages
        template: [persons, places]
  sidebar:
    width: 2/2
    sections:
      infoPagees:
        headline: Infoseiten
        type: pages
        template: [default]
  start:
    width: 2/2
    sections:
      startPage:
        headline: Startseite
        type: pages
        template: [startseite, help]
